### ISSUE TITLE
BitsAndBytes can't find CUDA when installed in venv, so can't use 8Bit DeepFloyd model

### ISSUE THREAD

**Issue by LiamSmyth** [threestudio-project/threestudio#58]
Hello! Amazing work!
Just up front, I'm not a researcher and am pretty noob to Linux and command line in general.

I was wondering if there was someone who could explain what I'm looking for to fix an issue related to bitsandbytes not being able to detect CUDA even though it detects CUDA :D 
I think it's related to this:
[BitsAndBy](https://github.com/TimDettmers/bitsandbytes/issues/112)

So I started by grabbing B&B and building it as in the instructions, after git cloning it to my users root directory. Setup.py fails when I am in a mamba venv: it complains about not having permissions to put the built files where it wants to. When I sudo run setup.py, it builds the files into "dist-packages" as an .egg folder which contains what I imagine is the built repo. Replacing the venv repo with the freshly built bitsandbytes folder gets rid of the "BitsandBytes not built for CUDA" but it then complains about duplicate .so for cudart.so and such. 

I have "taken it from the top" a few times with this repo, even deleting my ubuntu virtual drive and making it again a few times to ensure it's squeaky clean (only cuda 11.8 installed) 
I'm amazed at its functionality! But it would be even cooler to be able to use the 8bit model :D 

> 
> and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /home/lks/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
> /home/lks/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
>   warn("The installed version of bitsandbytes was compiled without GPU support. "
> /home/lks/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/lks/mambaforge/envs/threestudio/lib/libcudart.so.11.0'), PosixPath('/home/lks/mambaforge/envs/threestudio/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
> Either way, this might cause trouble in the future:
> If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
>   warn(msg)
> CUDA exception! Error code: no CUDA-capable device is detected
> CUDA exception! Error code: initialization error
> CUDA SETUP: CUDA runtime path found: /home/lks/mambaforge/envs/threestudio/lib/libcudart.so.11.0
> /home/lks/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
>   warn(msg)
> CUDA SETUP: Detected CUDA version 118
> CUDA SETUP: Loading binary /home/lks/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...

**Comment by LiamSmyth** [comment]
Aaaand I was able to follow the thread 
https://github.com/TimDettmers/bitsandbytes/issues/112#issuecomment-1504808954

there, though I had to do things a little differently:
My CUDA was installed in: /usr/local/cuda-11.8/

which meant I had to add /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcuda.so to PATH using 

`export PATH=$PATH:/usr/local/cuda-11.8/targets/x86_64-linux/lib/`

Lastly, I had to sim link libcuda from wsl to that folder that was added to path:

`ln -s /usr/lib/wsl/lib/libcuda.so /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcuda.so`

Hopefully this helps someone if they get blocked by BitsAndBytes!

**Comment by bennyguo** [comment]
Hi @LiamSmyth ! I was just reading your initial comment and found the problem to be solved when I scroll down 😂
Thank you for sharing! I'm sure this would help!

**Comment by bennyguo** [comment]
By the way, just to clarify, the 8-bit model is just the text encoder part of DeepFloyd-IF (T5-XXL). The (diffusion) image generation part still uses float16 and does not require BnB :)

**Comment by Acelogic** [comment]
Just writing here for the googlers 

I fixed this issue in my WSL by just adding 
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

to my .bashrc

**Comment by claforte** [comment]
Sounds like this issue is resolved. How about we close it?
