### ISSUE TITLE
multi-gpu training gets get stuck

### ISSUE THREAD

**Issue by ShoufaChen** [threestudio-project/threestudio#81]
Hi,

Thanks for your awesome code.

When I use four V100 GPUs, the program gets stuck as following:

```
(base)$ python launch.py --config configs/dreamfusion-if.yaml --train --gpu 0,1,2,3 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes" data.batch_size=2 data.n_val_views=4

[WARNING] Timestamp is disabled when using multiple GPUs, please make sure you have a unique tag.
Global seed set to 0

[INFO] ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
[INFO] Using 16bit Automatic Mixed Precision (AMP)
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[rank: 0] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[rank: 1] Global seed set to 0
[rank: 3] Global seed set to 0
[rank: 2] Global seed set to 0
[rank: 3] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
[rank: 2] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
[rank: 1] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
```

Could you please give some hints about this probmle? Thanks in advance.

**Comment by thuliu-yt16** [comment]
Could you see two processes on one of the GPUs? Because the prompt processor will spawn a process to embed the text for all GPUs. Maybe the process got stuck.

**Comment by ShoufaChen** [comment]
Hi @thuliu-yt16 ,

Thanks for your reply. Could you give more details how to 'see two processes on one of the GPUs'?

There is no error when I use one gpu for training:
```
python launch.py --config configs/dreamfusion-if.yaml --train --gpu 0 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"
```.

**Comment by bennyguo** [comment]
could you try running with `--verbose` and see where it get stuck? this will print more information

**Comment by ShoufaChen** [comment]
I solved it by modify `os.environ["MASTER_ADDR"]` from default `'127.0.0.1'` to `'localhost'`, in file `.../site-packages/lightning_fabric/utilities/distributed.py: def _init_dist_connection`

**Comment by bennyguo** [comment]
Glad it's solved. But it's a very weird problem (and a very weird solution too). Did you turn on any network proxy?
